import tkinter as tk
class view:
    def __init__(self, window):
        window = tk.Tk()
        window.geometry("500x500")
        window.mainloop
    entry01 = tk.Entry(width=3, font=3, bd=2)
    entry1 = tk.Entry(width=3, font=3, bd=2)
    entry2 = tk.Entry(width=3, font=3, bd=2)
    entry3 = tk.Entry(width=3, font=3, bd=2)
    entry_Plus = tk.Entry(width=3, font=3)
    entry02 = tk.Entry(width=3, font=3, bd=2)
    entry11 = tk.Entry(width=3, font=3, bd=2)
    entry22 = tk.Entry(width=3, font=3, bd=2)
    entry33 = tk.Entry(width=3, font=3, bd=2)
    entry_Equals = tk.Entry(width=22, font=3, bd=2)
    entry_Result = tk.Entry(width=3, font=3, bd=2)
    entry_Result1 = tk.Entry(width=3, font=3, bd=2)
    entry_Result2 = tk.Entry(width=3, font=3, bd=2)
    entry_Result3 = tk.Entry(width=3, font=3, bd=2)
    entry_Result4 = tk.Entry(width=3, font=3, bd=2)
    button = tk.Button(text="Проверка", width=20, height=2)
    button1 = tk.Button(text="Следующая головоломка", width=20, height=2)
    lbl = tk.Label(text="Введите результат ->", width=20, font=1, bd=2)
    entry_ResultAll = tk.Entry(width=10, font=3, bd=2)
    entry_Correct = tk.Entry(width=15, font=3, bd=2, state='disabled')
    entry01.insert(0, "О")
    entry1.insert(0, "Д")
    entry2.insert(0, "И")
    entry3.insert(0, "Н")
    entry_Plus.insert(0, "+")
    entry02.insert(0, "О")
    entry11.insert(0, "Д")
    entry22.insert(0, "И")
    entry33.insert(0, "Н")
    entry_Equals.insert(0, "---------------------------------------")
    entry_Result.insert(0, "М")
    entry_Result1.insert(0, "Н")
    entry_Result2.insert(0, "О")
    entry_Result3.insert(0, "Г")
    entry_Result4.insert(0, "О")
    entry_Correct.insert(0, "Ответ: ")
    entry01.grid(padx=10, pady=10)
    entry1.grid(column=1, row=0, padx=1, pady=10)
    entry2.grid(column=2, row=0, padx=20, pady=10)
    entry3.grid(column=3, row=0, padx=20, pady=10)
    entry_Plus.grid(column=0, row=1, pady=10)
    entry02.grid(column=0, row=2, pady=10)
    entry11.grid(column=1, row=2, pady=10)
    entry22.grid(column=2, row=2, pady=20)
    entry33.grid(column=3, row=2, pady=20)
    entry_Equals.grid(columnspan=6, row=3, pady=10)
    entry_Result.grid(column=0, row=4, pady=10)
    entry_Result1.grid(column=1, row=4, pady=10)
    entry_Result2.grid(column=2, row=4, pady=10)
    entry_Result3.grid(column=3, row=4, pady=10)
    entry_Result4.grid(column=4, row=4, pady=10)
    button.grid(columnspan=2, row=5, pady=10)
    button1.grid(column=3, columnspan=2, row=5)
    lbl.grid(column=0, columnspan=3, row=6)
    entry_ResultAll.grid(column=3, row=6)
    entry_Correct.grid(column=1, row=7, pady=10, padx=10)
